---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-kyverno-vpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo
 namespace: demo-kyverno-vpa
spec:
 selector:
   matchLabels:
     app: demo
 replicas: 1
 template:
   metadata:
     labels:
       app: demo
   spec:
     containers:
     - name: demo
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
           memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
 name: demo
 namespace: demo-kyverno-vpa
 labels:
   app: demo
spec:
 ports:
 - port: 80
 selector:
   app: demo
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: demo-deployment
 namespace: demo-kyverno-vpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: demo
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50
