---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-vpa
  annotations:
    policies.kyverno.io/title: Generate VPA
    policies.kyverno.io/category: Resource Optimization
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy generates Vertical Pod Autoscalers (VPAs)
      for Deployment and StatefulSet resources.
spec:
  # uncomment the following line to generate VPAs for existing resources
  generateExisting: true
  rules:
    - name: create-for-podcontrollers
      match:
        any:
        - resources:
            kinds:
              - Deployment      
              - StatefulSet
      generate:
        synchronize: true
        kind: VerticalPodAutoscaler
        apiVersion: autoscaling.k8s.io/v1
        name: "{{request.object.metadata.name}}-kyverno" 
        namespace: "{{request.object.metadata.namespace}}"
        data:
          spec:
            targetRef:
              apiVersion: "{{request.object.apiVersion}}"
              kind: "{{request.object.kind}}"
              name: "{{request.object.metadata.name}}"
            updatePolicy:
              updateMode: "Off" 
